#!/usr/bin/env bash

echo "=============================="
echo "       ArchTower Info"
echo "=============================="
echo

date
echo

fastfetch
echo

echo "Dotfiles:"
git -C "$HOME/dotfiles" log --oneline -1
